use anyhow::Result;
use sxg_rs::config::Config as SxgConfig;
use sxg_rs::crypto::EcPrivateKey;

const CONFIG_YAML: &str = "http_server/config.yaml";
const PRIVKEY_PEM: &str = "credentials/privkey.pem";

pub(crate) fn main(mut config: SxgConfig) -> Result<()> {
    config.private_key_base64 = Some(base64::encode(
        EcPrivateKey::from_sec1_pem(&std::fs::read_to_string(PRIVKEY_PEM)?)?.d,
    ));
    std::fs::write(
        CONFIG_YAML,
        format!(
            "# This file is generated by command \"cargo run -p tools -- gen-config\".\n\
            # Please note that anything you modify won't be preserved\n\
            # at the next time you run \"cargo run -p tools -- -gen-config\".\n\
            {}",
            serde_yaml::to_string(&config)?,
        ),
    )?;
    Ok(())
}
