# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "sxg_rs"
version = "0.1.0"
authors = ["9083193+antiphoton@users.noreply.github.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["strip_id_headers"]
rust_signer = []
strip_id_headers = []
wasm =[]

[dependencies]
anyhow = "1.0.44"
async-trait = "0.1.51"
base64 = "0.13.0"
der-parser = { version = "6.0.0", features = ["bigint", "serialize"] }
futures = { version = "0.3.17", features = ["executor"] }
getrandom = { version = "0.2.3", features = ["js"] }
js-sys = "0.3.55"
nom = { version = "6.2.1", features = ["alloc"] }
once_cell = "1.8.0"
p256 = { version = "0.9.0", features = ["ecdsa"] }
pem = "0.8.3"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
sha2 = "0.9.8"
url = "2.2.2"
wasm-bindgen = { version = "0.2.78", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.28"
web-sys = { version = "0.3.55", features = ["console"] }
x509-parser = "0.12.0"

[dev-dependencies]
async-std = { version = "1.10.0", features = ["attributes"] }
